baseURL = 'https://davidmorenohirschportfolio.netlify.app//'
languageCode = 'en-us'
title = 'David Moreno-Hirsch Portfolio'

theme = "hugo-xterm"

showDate = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
